version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile.web
    container_name: photobooth-web
    restart: unless-stopped
    volumes:
      - ./static/frames:/app/static/frames
      - ./photos:/app/photos
      - ./config:/app/config
    environment:
      - FLASK_ENV=production
    networks:
      - photobooth

  nginx:
    build:
      context: .
      dockerfile: docker/Dockerfile.nginx
    container_name: photobooth-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/ssl:/etc/nginx/ssl:ro
      - ./static:/var/www/static:ro
    depends_on:
      - web
    networks:
      - photobooth

networks:
  photobooth:
    driver: bridge
